# Generated by Django 5.0.1 on 2024-02-07 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username should contain only letters, numbers, points (.) and dashes (-).', regex='^[a-zA-Z0-9.-]{4, }$'), django.core.validators.RegexValidator(code='invalid_username', inverse_match=True, message='Username not allowed, pertains to reserved list.', regex='^(login|logout|register|following)+$')]),
        ),
    ]
