# Generated by Django 5.0.1 on 2024-02-07 16:20

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username should contain only letters, numbers, points (.) and dashes (-).', regex='^[a-zA-Z0-9.-]{4,}$'), django.core.validators.RegexValidator(code='invalid_username', inverse_match=True, message='Username not allowed, pertains to reserved list.', regex='^(login|logout|register|following)+$')]),
        ),
    ]
