# Generated by Django 5.0.1 on 2024-02-12 11:08

import courses.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', courses.models.UserManager()),
            ],
        ),
    ]
