# Generated by Django 5.0.1 on 2024-02-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_user_id_category_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='term_id',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='coursesection',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='course_section_id',
            new_name='course_section',
        ),
    ]
