# Generated by Django 5.0.1 on 2024-02-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_hours_forecast_alter_log_time_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours_forecast',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
