# Generated by Django 5.0.1 on 2024-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_hours_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='website',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
