# Generated by Django 5.0.1 on 2024-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursesection_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='website',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
