# Generated by Django 5.0.1 on 2024-02-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_spent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
