# Generated by Django 5.0.1 on 2024-02-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_log_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
