# Generated by Django 5.0.1 on 2024-02-13 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='log',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursesection'),
        ),
    ]
