# Generated by Django 5.0.1 on 2024-02-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_coursesection_course_alter_log_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursesection_set', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='log',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_set', to='courses.coursesection'),
        ),
    ]
